#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [2]:
import numpy as np

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [3]:
import numpy as np

Z = np.random.randint(0,2,(6,3))
Z

array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [6]:
uZ = np.unique(Z, axis=0)
uZ

array([[0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])

#### 72. How to swap two rows of an array? (★★★)

In [13]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [34]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)

D_means = D_sums / D_counts
D_means

array([0.54307691, 0.51364438, 0.49330766, 0.40562021, 0.49664603,
       0.51962535, 0.48368138, 0.50674849, 0.65401482, 0.53072337])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [50]:
Z = np.array([1,2,3,4,5])
n_zero = 3
Z_ = np.zeros((len(Z)-1)*n_zero + len(Z))
Z_[::n_zero+1] = Z
Z_

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

In [48]:
A = np.arange(10)
A[::3]

array([0, 3, 6, 9])